#!/bin/bash

# Inclusive firewall rules: block any input except SSH from home/work or already established connections.

homeip="37.110.91.2"
workip="91.241.13.26/24"

iptables -F

# Allow local programs that use loopback (Unix sockets)
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Allow all icmp
iptables -A INPUT -p icmp -j ACCEPT

# Allow established connections
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# SSH
iptables -A INPUT -p tcp -s $homeip --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp -s $workip --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

# Nginx 80
iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
#iptables -A INPUT -p tcp -s $workip --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

# Drop invalid packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP

iptables -A FORWARD -i eth0 -o lo -j ACCEPT
iptables -A FORWARD -i lo -o eth0 -j ACCEPT

iptables -A INPUT -j LOGGING
iptables -A LOGGING -j LOG --log-prefix "NETFILTER " --log-level 7
iptables -A LOGGING -j DROP

# Default policy to drop 'everything' but our output to internet
iptables -P FORWARD DROP
iptables -P INPUT   DROP
iptables -P OUTPUT  ACCEPT
